// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAhmQt66V-2Oi59vAmxKj7xhcsn8Hkbvvw',
    appId: '1:204826299859:web:5bc6f3bf526321fbe73326',
    messagingSenderId: '204826299859',
    projectId: 'repsoft-8cd5c',
    authDomain: 'repsoft-8cd5c.firebaseapp.com',
    storageBucket: 'repsoft-8cd5c.appspot.com',
    measurementId: 'G-FHDKQ075CC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC0kz9cWsWIy8ZvgOGPkzLpM-sUXoIQ8nk',
    appId: '1:204826299859:android:8133c237e76eaf00e73326',
    messagingSenderId: '204826299859',
    projectId: 'repsoft-8cd5c',
    storageBucket: 'repsoft-8cd5c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB8ErFOoZa7tFHQPCaDu4k6wSoKNGy51Eo',
    appId: '1:204826299859:ios:594939679bbcf6f2e73326',
    messagingSenderId: '204826299859',
    projectId: 'repsoft-8cd5c',
    storageBucket: 'repsoft-8cd5c.appspot.com',
    iosBundleId: 'com.example.assesment',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB8ErFOoZa7tFHQPCaDu4k6wSoKNGy51Eo',
    appId: '1:204826299859:ios:594939679bbcf6f2e73326',
    messagingSenderId: '204826299859',
    projectId: 'repsoft-8cd5c',
    storageBucket: 'repsoft-8cd5c.appspot.com',
    iosBundleId: 'com.example.assesment',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAhmQt66V-2Oi59vAmxKj7xhcsn8Hkbvvw',
    appId: '1:204826299859:web:56dd7c8e79736d39e73326',
    messagingSenderId: '204826299859',
    projectId: 'repsoft-8cd5c',
    authDomain: 'repsoft-8cd5c.firebaseapp.com',
    storageBucket: 'repsoft-8cd5c.appspot.com',
    measurementId: 'G-L3PFMLEFJF',
  );
}
